export const INITIAL_STATE = 'INITIAL_STATE';
export const SAVE_CURRENT_MUSIC = 'SAVE_CURRENT_MUSIC';
export const CHANGE_ISCURRENTSONG = 'CHANGE_ISCURRENTSONG';
export const CHANGE_PLAYING = 'CHANGE_PLAYING';
export const CHANGE_ISCHANGEPLAYING = 'CHANGE_ISCHANGEPLAYING';
